### ISSUE TITLE
Queried informations not exhibited when `-W, --wait`  is invoked

### ISSUE THREAD

**Issue by Ricky-Tigg** [a-j-wood/pv#61]
pv v. **1.6.20**

Hello. To reproduce:
```
$ mkdir 0; touch 0/{0,1}; rm -r --interactive=once 0/ | pv -Wprab
rm: remove 1 argument recursively? y
$  
```
Then `0,00 B [0,00 B/s] [0,00 B/s] [<=>]`, which is the expected output from `pv`, is not exhibited.

`pv` behaves as intended by exhibiting queried informations  when `-W, --wait`  is not invoked; e.g. `mkdir 0; touch 0/{0,1}; rm -r 0/ | pv -prab`.

**Comment by a-j-wood** [comment]
PV is reading from standard input, "rm" will be writing its queries to standard error or the terminal device, not standard output, so PV doesn't see any input.  With "--wait", PV will output nothing until it sees some input.

To confirm this please try redirecting to a file instead of piping to PV.  You should see that the resultant file is empty.

If you don't actually want the interactive query from "rm" then "rm -rv 0/ 2>&1 | pv" should give you a progress display of sorts.  The "-v" option to "rm" will tell it to show what it's doing, probably on standard error hence the 2>&1 to send standard error to standard output where it can be piped to PV.

**Comment by Ricky-Tigg** [comment]
```
$ rm -r --interactive=once 0/ >00
rm: remove 1 argument recursively? y
$ cat 00
$ 
```
Assuming the necessity of interactive mode in main command. Yet that `-W`? I could not deduce upon your comment a command that demonstrates it to be operational. An example of yours is welcome.

**Comment by a-j-wood** [comment]
Unix and Linux processes have 1 default input stream, "standard input", and 2 default output streams, one for normal output - "standard output" - and one for errors - "standard error".

When you run a command by itself on a terminal, both standard output and standard error are written to the terminal.

When you redirect a command's output to a file with ">", you are redirecting its standard output.  Standard error is still written to the terminal, unless you use "2>".

When you use a pipe between processes, you are connecting the standard output of the first process to the standard input of the second process.  The standard error is still written to the terminal.

The "rm" command is writing the information you see, to its standard error stream, not to its standard output stream.

You can see this by your ">00" in the commands you posted.  You saw that the file "00" ended up empty.  This was because "rm" wrote the information you saw on the terminal to its standard error stream, so it showed up on the terminal, but was not sent to the file.

Similarly, when you put "| pv" instead of ">00", the standard output of "rm" will go to the input of "pv".  And like the ">00" example, "rm" will write nothing to it.

So since "pv -W" is telling "pv" to wait until it sees any input, it will never display anything, because "rm" is not writing anything to it.

It does not look like there is any way to make "rm" and "pv" work together in the way that you want.  In the tests I've tried, "rm" is always writing its information to the standard error stream, and since you want to be able to see that first prompt from "rm" on the terminal, you can't do "2>&1" to merge standard error with standard output and send to "pv".
