### ISSUE TITLE
pv 1.7.18 doesn't use the whole terminal width

### ISSUE THREAD

**Issue by andrew-schulman** [a-j-wood/pv#72]
In Cygwin, the output of pv 1.7.18 is always 80 characters wide, even when the terminal is wider, for example 199 columns as here:

```
$ pv -S -s 100G < /dev/zero > /dev/null
 100GiB 0:00:11 [8.73GiB/s] [================================>] 100%

$ echo $COLUMNS
199
```
pv 1.7.0 does use the whole terminal width in Cygwin.

**Comment by a-j-wood** [comment]
Confirmed that I can reproduce this on my own Cygwin installation using the example you have provided.

The fault appears to be caused by the configure and autoheader changes.  In `src/pv/display.c` there is a check for "`HAVE_TERMIOS_H`", but this is no longer defined in `config.h`.

As a short term workaround, after running "`configure`", edit `src/include/config.h` and add

    #define HAVE_TERMIOS_H 1

to the end of it, then run "`make`".

I have committed a fix to the main branch.  If you would like to confirm that it works for you, please download the latest code (e.g. "`git clone https://github.com/a-j-wood/pv.git`") and then run "`./generate.sh && ./configure && make`".  Thanks.

**Comment by andrew-schulman** [comment]
Confirmed that the problem is fixed in main. Thanks! Once you make a new release I'll push it out to Cygwin.

**Comment by a-j-wood** [comment]
Thanks.  A new release is imminent, since I expect that this fault was not confined only to the Cygwin platform.

**Comment by a-j-wood** [comment]
Version 1.7.24 now released.
